version: "3.8"

services:
  app:
    build: .
    container_name: express-app
    ports:
      - "${PORT}:80"
    environment:
      - DATABASE_URL=postgresql://snack:snack@postgres:5432/snack
      - ACCESS_TOKEN_SECRET=snack
      - REFRESH_TOKEN_SECRET=snack
      - PORT=80
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      - POSTGRES_USER=snack
      - POSTGRES_PASSWORD=snack
      - POSTGRES_DB=snack
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"

volumes:
  pgdata:
